# Generated by Django 5.1.2 on 2024-11-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_administrator_email_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.classe'),
        ),
    ]
