# Generated by Django 5.1.2 on 2024-11-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_department_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
