# Generated by Django 5.1.2 on 2024-11-13 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_classe_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='creationdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
