# Generated by Django 5.1.2 on 2024-11-13 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_classe_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='creationdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='creationdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='creationdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
