# Generated by Django 5.1.2 on 2024-11-13 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_administrator_creationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='creationdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mark',
            name='creationdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='creationdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
