# Generated by Django 5.1.2 on 2024-11-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lecturer_usersname_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.administrator'),
        ),
    ]
