# Generated by Django 5.1.2 on 2024-12-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mark_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
