# Generated by Django 5.1.2 on 2024-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mark_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
