# Generated by Django 5.1.2 on 2024-12-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_mark_year_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
